[package]
name = "rust_scripts"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
solana-client = "1.18.6"
solana-program = "1.18.6"
solana-sdk = "1.18.6"
spl-token = "4.0.0"

