[package]
name = "create_account"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-client = "1.17.5"
solana-program = "1.17.5"
solana-sdk = "1.17.5"
