[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
vault = "857qXVVHUu3rXin47Bm9y3FpLohTwBW8s8V3pkcwXa4F"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/renzo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
