[features]
seeds = false
skip-lint = false
[programs.localnet]
vault = "4VHHjyCG5NpU2pApDo2MDS8RQXKoNvHLmWKXWqDqVrp1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/renzo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 9000000 tests/**/*.ts"
