[features]
seeds = false
skip-lint = false
[programs.localnet]
anoni_dapp = "APuJFWdT3ofWahwQDrAkKz5ndU8TPoTeX2QVV2rYu1NU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/renzo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
