[features]
seeds = false
skip-lint = false
[programs.localnet]
crowdfunding = "9PLX14T3S41p2wbzNtt8kUWLX2JX6kkTL2mjuwW753fC"
[programs.devnet]
crowdfunding = "9PLX14T3S41p2wbzNtt8kUWLX2JX6kkTL2mjuwW753fC"
[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/renzo/.config/solana/id.json "

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
