[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_vault = "8c3EenM7ZSzEpC121jPdbrKgvQxM1iBaXjfHyzZuG1V2"

[programs.devnet]
anchor_vault = "8c3EenM7ZSzEpC121jPdbrKgvQxM1iBaXjfHyzZuG1V2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
