[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
express_todo = "DSKk1maqJij5xqjFqgJNcKgo8sKgRzGZjjr1BWRFP4dP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/renzo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
