[features]
seeds = false
skip-lint = false
[programs.localnet]
send_my_ft = "Hnw8dS2JHykAYJoHnFGVNTzmSxQ5dYaaaSJ9t5HCt69b"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/renzo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 9000000 tests/**/*.ts"

[test]
startup_wait = 20000