[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
project_01 = "FbJHAAHCeHDdgPfAmt3z3HybinuLcZyra2H2CTwSkCJa"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/renzo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
