[features]
seeds = false
skip-lint = false
[programs.localnet]
mycalculatordapp = "2o1gunmicBkWGKoGcSc4T19Wo12wxZcn5qhkNcqS1WJx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/renzo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
