[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
string_saver_dapp = "4EZmVGSvLdh7J25EftVKE4rs1SwmGqnCkn4DdmbQF5oJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/renzo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
