[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
node_string_saver = "LwLEiVLfLitKwkTSo6rScZspxTF1PfeEX8HBp71LCHE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/renzo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
