[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
send_sol = "5it2J1fobXmPnZGgDPaaq5j4o4dGoFtGxGHnt9BHipHB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/renzo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
